ems/urls.py
from django.urls import path

from ems import views

app_name = 'ems'

urlpatterns = [
    path("index/", views.index, name='index'),
    path("del_s/", views.del_session, name='del_s'),
    path("del/", views.deluser, name='del'),
    path("add/", views.adduser, name='add'),
    path("add2/", views.adduser2, name='add2'),
    path("update/", views.updateuser, name='update'),
    path("update2/", views.updateuser2, name='update2'),
]

one_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('ems/', include('ems.urls')),
]

ems/models.py
from django.db import models


# Create your models here.

class Department(models.Model):
    dept_name = models.CharField(max_length=20)

    class Meta:
        db_table = 'dept'


class Employee(models.Model):
    name = models.CharField(max_length=20)
    age = models.SmallIntegerField()
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    birthday = models.DateField(auto_now_add=True, null=True)
    gender = models.BooleanField()
    photo = models.ImageField(upload_to='img')
    dept = models.ForeignKey(to="Department", on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        db_table = 'employee'

ems/views.py
import os
from uuid import uuid4

from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from ems.models import Employee, Department


def del_session(request):
    request.session.flush()
    return render(request,'user/login.html')

def adduser(request):
    dept_list = Department.objects.all()
    return render(request,'ems/add.html',{'dept_list':dept_list})

def adduser2(request):
    username = request.POST.get('name')
    age = request.POST.get('age')
    salary = request.POST.get('salary')
    img_head = request.FILES.get('photo')
    print(img_head)
    sex = request.POST.get('sex')
    dept = request.POST.get('dept')
    extend = os.path.splitext(img_head.name)[1]
    # 获取后缀名
    img_head.name = str(uuid4()) + extend
    # 重命名,对图片文件无规则命名
    age = int(age)
    emp = Employee.objects.create(name=username, age=age, salary=salary, photo=img_head,gender=sex,dept_id=dept)
    if emp:
        return redirect("http://127.0.0.1:8000/ems/index/")
    else:
        return HttpResponse('添加失败')

def deluser(request):
    id = request.GET.get('id')
    emp = Employee.objects.get(id=id)
    emp.delete()
    return redirect("http://127.0.0.1:8000/ems/index/")

def updateuser(request):
    id = request.GET.get('id')
    return render(request,'ems/update.html',{'id':id})

def updateuser2(request):
    id = request.GET.get('id')
    name = request.POST.get('name')
    age = request.POST.get('age')
    salary = request.POST.get('salary')
    age = int(age)
    emp = Employee.objects.get(id=id)
    emp.name = name
    emp.age = age
    emp.salary = salary
    emp.save()
    return redirect("http://127.0.0.1:8000/ems/index/")

from django.core.paginator import Paginator


def index(request):
    a = request.session.get('is')
    name = request.session.get('name')
    emp_list = Employee.objects.all()
    # 获取前端传递的参数，通过此参数决定获取第几页的数据
    number = int(request.GET.get("number", 1))
    # 初始化一个分页器对象
    paginator = Paginator(object_list=emp_list, per_page=2)
    # 获取页面对象
    page = paginator.page(number)
    if a:
            return render(request,'ems/index.html',{'name':name,'page':page})
    else:
        return redirect('/user/login')

templates/ems/add.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">Main</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>
        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                add Emp info:
            </h1>
            <form action="{% url 'ems:add2' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">name:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="name"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">salary:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="salary"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">age:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="age"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">头像:</td>
                        <td valign="middle" align="left">
                            <input type="file" name="photo"/>
                        </td>
                    </tr>
{#                    <tr>#}
{#                        <td valign="middle" align="right">生日:</td>#}
{#                        <td valign="middle" align="left">#}
{#                            <input type="date" class="inputgri" name="bir"/>#}
{#                        </td>#}
{#                    </tr>#}
                    <tr>
                        <td valign="middle" align="right">性别:</td>
                        <td valign="middle" align="left">
                            <select name="sex" id="">
                                <option value="0">男</option>
                                <option value="1">女</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">部门:</td>
                        <td valign="middle" align="left">
                            <select name="dept" id="">
                                {% for dept in dept_list %}
                                    <option value="{{ dept.id }}">{{ dept.dept_name }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>

                </table>
                <p>
                    <input type="submit" class="button" value="确定添加"/>
                </p>
            </form>
            <a href="{% url 'ems:index' %}">返回首页</a>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            ABC@126.com
        </div>
    </div>
</div>
</body>
</html>

templates/ems/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
<h2></h2>
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">main</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>
        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                欢迎{{ name }}登录
                <a href="{% url 'ems:del_s' %}">退出</a>
            </h1>
            <table class="table">
                <tr class="table_header">
                    <td>ID</td>
                    <td>Name</td>
                    <td>Salary</td>
                    <td>Age</td>
                    <td>生日</td>
                    <td>性别</td>
                    <td>照片</td>
                    <td>部门</td>
                    <td>Operation</td>
                </tr>
                {% for emp in page %}
                    <tr class="row1">
                        <td>{{ emp.id }}</td>
                        <td>{{ emp.name }}</td>
                        <td>{{ emp.salary }}</td>
                        <td>{{ emp.age }}</td>
                        <td>{{ emp.birthday}}</td>
                        <td>{{ emp.gender}}</td>
                        <td><img src="{% static emp.photo.url %}" alt="无法加载"  height="50px" width="50px"></td>
                        <td>{{ emp.dept_id }}</td>
                        <td>
                            <a href="/ems/del/?id={{ emp.id }}">删除</a>|<a href="/ems/update/?id={{ emp.id }}">修改</a></td>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <p>
                <a href="{% url 'ems:add' %}">添加员工</a>
            </p>
        </div>
    </div>
    <h4 style="color: #5494F3">
    {#    上一页#}
        {% if page.has_previous %}
    {#        获取上一页页码#}
        <a href="/ems/index/?number={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        {% for n in page.paginator.page_range %}
            {% if page.number == n %}
            <a class="b" href="/ems/index/?number={{ n }}">{{ n }}</a>
            {% else %}
            <a class="a" href="/ems/index/?number={{ n }}">{{ n }}</a>
            {% endif %}
        {% endfor %}
    {#    下一页#}
        {% if page.has_next %}
    {#        获取下一页页码#}
        <a href="/ems/index/?number={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </h4>
    <div id="footer">
        <div id="footer_bg">
            ABC@126.com
        </div>
    </div>
</div>
</body>
</html>

templates/ems/update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">Main</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>
        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                update Emp info:
            </h1>
            <form action="http://127.0.0.1:8000/ems/update2/?id={{ id }}" method="post">
                 {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">
                            id:
                        </td>
                        <td valign="middle" align="left">
                            {{ id }}
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            name:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="name" value="zhangshan"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            salary:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="salary" value="20000"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            age:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="age" value="20"/>
                        </td>
                    </tr>
                </table>
                <p>
                    <input type="submit" class="button" value="提交"/>
                </p>
            </form>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            ABC@126.com
        </div>
    </div>
</div>
</body>
</html>