ems/urls.py
from django.urls import path

from ems import views

app_name = 'ems'

urlpatterns = [
    path("index/", views.index, name='index'),
    path("del_s/", views.del_session, name='del_s'),
    path("del/", views.deluser, name='del'),
    path("add/", views.adduser, name='add'),
    path("add2/", views.adduser2, name='add2'),
    path("update/", views.updateuser, name='update'),
    path("update2/", views.updateuser2, name='update2'),
]

one_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('ems/', include('ems.urls')),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("user_register/", views.user_register, name="user_register"),
    path("send_email/", views.send_email, name="send_email"),
    path("login/", views.login, name="login"),
    path("login2/", views.login2, name="login2"),
    path("captcha/", views.captcha, name="captcha"),
    path("ce2/", views.checkEmail2, name="ce2"),
    path("checkEmail2/", views.checkEmail2, name="checkEmail2"),
    path("checkPhone2/", views.checkPhone2, name="checkPhone2"),
]

user/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=32)
    sex = models.BooleanField(default=True, verbose_name="True为男")
    phone = models.CharField(max_length=11)
    salt = models.CharField(max_length=8, default=None, null=True)

    class Meta:
        db_table = 'user'

user/views.py
import random
import string

from django.db import transaction
from django.db.models import Q
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.http import HttpResponse, response
from django_redis import get_redis_connection
from redis import Redis

from user.captcha.image import ImageCaptcha
# Create your views here.
from user.models import User
from user.utils.hash_code import hash_pwd, hash_email
from user.utils.salt import get_salt


def captcha(request):
    img = ImageCaptcha()
    cc = random.sample(string.ascii_letters + string.digits, 4)
    cc = "".join(cc)

    data = img.generate(cc)
    # 返回二进制数据

    request.session['captcha'] = cc
    return HttpResponse(data, "img/png")


def register(request):
    return render(request, "user/register.html")


def user_register(request):
    # 1. 获取前端传递的参数并判断参数是是否合法
    phone = request.POST.get("phone")
    email = request.POST.get("email")
    pwd = request.POST.get("user_pwd")
    sex = request.POST.get("sex")
    email_code = request.POST.get("email_code")
    if sex == 'm':
        sex = True
    else:
        sex = False
    # 2. 比对邮箱验证码是否一致

    # redis = Redis(host="192.168.92.128", port=7000)
    # code = redis.get(email)
    # redis.setex(email,300,code)
    # redis_connection = get_redis_connection("default")
    # code = redis_connection.get(email)

    # 如果code不存在，则代表验证码已过期
    code = request.session.get('code')
    if email_code != code:
        return HttpResponse("邮箱验证码不一致")
    # 3. 将用户的数据保存至数据库
    salt = get_salt()
    hash_password = hash_pwd(pwd, salt)
    number = request.POST.get('number')
    cc2 = request.session.get('captcha')
    number = number.lower()
    cc2 = cc2.lower()
    with transaction.atomic():
        if (number == cc2):
            user = User.objects.create(email=email, phone=phone, password=hash_password, sex=sex,salt=salt)
            if user:
                return redirect("/user/login")
        else:
            return HttpResponse('验证码错误')
    # 4. 如果对象保存成功，重定向到渲染登录页面的视图
    return redirect("user:login")


def send_email(request):
    request.session.flush()
    email = request.GET.get("email")
    subject = "欢迎您注册百知教育员工系统"
    # 随机验证码
    code = random.sample(string.digits,6)
    code = ''.join(code)
    # 在发送验证码时需要将验证码储存起来，方便注册时验证，并设置验证码的有效期
    if request.session.get('code'):
        del request.session['code']
    request.session['code'] = code
    # redis = Redis(host="192.168.92.128", port=7000)
    # redis.setex(email, 300, code)
    # redis_connection = get_redis_connection("default")
    # redis_connection.setex(email, 300, code)
    # request.session['code'] = code
    # 判断email以及email是否合法
    if email:
        status = send_mail(
            subject,
            f"这是您的注册码{code}，请在5分钟内完成注册",
            "3202448109@qq.com",
            [email],
        )
        if status:
            return HttpResponse("邮件发送成功")
    return HttpResponse("邮件发送失败，请稍等")


def login(request):
    try:
        name = request.COOKIES.get('name')
        pwd = request.COOKIES.get('pwd')
        with transaction.atomic():
            user = User.objects.filter(Q(email=name, password=pwd) | Q(phone=name, password=pwd)).first()
            if user:
                request.session['is'] = True
                request.session['name'] = name
                return redirect('http://127.0.0.1:8000/ems/index/')
            else:
                return render(request,"user/login.html")
    except:
        return render(request,"user/login.html")

def login2(request):
    try:
        name = request.POST['name']
        pwd = request.POST['pwd']
        check = request.POST.get('check')
        with transaction.atomic():
            user = User.objects.filter(Q(email=name) | Q(phone=name)).first()
            salt = user.salt
            # 再次对密码进行加密对比
            hash_pwd1 = hash_pwd(pwd, salt)
            user = User.objects.filter(Q(email=name, password=hash_pwd1) | Q(phone=name, password=hash_pwd1))
            if user:
                request.session['is'] = True
                request.session['name'] = name
                if check == '1':
                    response = redirect('http://127.0.0.1:8000/ems/index/')
                    response.set_cookie('name',name,max_age=3600 * 24 * 7)
                    response.set_cookie('pwd',hash_pwd1 ,max_age=3600 * 24 * 7)
                    return response
                else:
                    response = redirect('http://127.0.0.1:8000/ems/index/')
                    return response
            else:
                return HttpResponse('用户名或密码错误')
    except:
        return HttpResponse('登录失败')

def checkEmail2(request):
    email = request.POST.get('email')
    user = User.objects.filter(email=email)
    if user:
        return HttpResponse('邮箱已存在')
    else:
        return HttpResponse()

def checkPhone2(request):
    phone = request.POST.get('phone')
    user = User.objects.filter(phone=phone)
    if user:
        return HttpResponse('手机号已存在')
    else:
        return HttpResponse()

def check(request):
    # 1. 接收到前端的参数
    name = request.GET.get("name")

    # 2. 查询用户名是否已存在
    user_set = User.objects.filter(Q(email=name) | Q(phone=name))
    if user_set:
        return HttpResponse("用户名已存在")

    return HttpResponse("")

templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>
                    2009/11/20
                    <br/>
                </p>
            </div>
            <div id="topheader">
                <h1 id="title">
                    <a href="#">main</a>
                </h1>
            </div>
            <div id="navigation">
            </div>
        </div>
        <div id="content">
            <p id="whereami">
            </p>
            <h1>
                login
            </h1>
            <form action="http://127.0.0.1:8000/user/login2/" method="post">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">
                            用户名:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="name"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            密　码:
                        </td>
                        <td valign="middle" align="left">
                            <input type="password" class="inputgri" name="pwd"/>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="left" colspan="2">
                            记住我：<input type="checkbox" value="1" name="check"><br>
                        </td>
                    </tr>
                </table>
                <p>
                    <input type="submit" class="button" value="登录 &raquo;"/>
                </p>
            </form>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            ABC@126.com
        </div>
    </div>
</div>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>
        function checkEmail(t) {
            // 处理相关的验证  只有通过验证后才为True
            let flag = true;
            let email = $("[name='email']").val();
            let pattern = /^[A-Za-z\d]+([-_.][A-Za-z\d]+)*@([A-Za-z\d]+[-.])+[A-Za-z\d]{2,4}$/
            if (email == null | email == "") {
                document.getElementById("email_msg").innerHTML = "邮箱不能为空";
            } else if (pattern.test(email) == false) {
                document.getElementById("email_msg").innerHTML = "邮箱格式错误";
            } else {
                document.getElementById("email_msg").innerHTML = "";
                flag = checkemail3(t)
                {#flag = true;#}
            }
            return flag;
        }

        // 检测手机号
        function checkPhone(t) {
            let flag = true;
            let phone = $("[name='phone']").val();
            let pattern =  /^1(3[0-9]|4[5,7]|5[0,1,2,3,5,6,7,8,9]|6[2,5,6,7]|7[0,1,7,8]|8[0-9]|9[1,8,9])\d{8}$/;
            if (phone == null | phone == "") {
                document.getElementById("phone_msg").innerHTML = "手机号不能为空";
            } else if (pattern.test(phone) == false) {
                document.getElementById("phone_msg").innerHTML = "手机号格式错误";
            } else {
                document.getElementById("phone_msg").innerHTML = "";
                {#flag = true;#}
                flag = checkphone3(t)
            }
            return flag;

        }

        function checkPwd() {
            // 初识标识为false，当通过所有验证后改为true
            let flag = false;
            // 获取用户输入的密码
            let user_pwd = $("[name='user_pwd']").val();
            // 对用户输入的密码强度进行判断  正则判断
            let pattern = /^[a-zA-Z][a-zA-Z0-9\_\.\@\!\#\$\%\^\&\*\(\)]{5,16}/;

            // 密码不能为空
            if (user_pwd == null | user_pwd == "") {
                document.getElementById("pwd_msg").innerHTML = "密码不能为空";
                // 正则校验密码强度
            } else if (pattern.test(user_pwd) == false) {
                document.getElementById("pwd_msg").innerHTML = "密码强度太低";
                // 代表校验通过
            } else {
                document.getElementById("pwd_msg").innerHTML = "";
                flag = true;
            }
            return flag;
        }

        function checkemail3(t) {
            // 声明一个对象
            let flag = false
            let xhr = new XMLHttpRequest();
            // 指定服务器地址与方法
            let url = "/user/checkEmail2/";
            xhr.open('post', url, true);
            // 发送请求 post请求需要在请求头中指定csrf
            xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
            xhr.send("csrfmiddlewaretoken={{ csrf_token }}&email=" + t.value);
            // 接收服务器返回的响应
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    let responseText = xhr.responseText;
                    // 更新页面
                    let span = document.getElementById("text1");
                    span.innerHTML = responseText;
                    if (span.innerHTML === true){
                        flag = false;
                        return flag
                    }
                    else {
                        flag = true;
                        return flag
                    }
                }
            }
        }

        function checkphone3(t){
            let flag = false;
            let xhr = new XMLHttpRequest();
            let url = "/user/checkPhone2/";
            xhr.open("post",url,true);
            xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
            xhr.send("csrfmiddlewaretoken={{ csrf_token }}&phone=" + t.value);
            xhr.onreadystatechange = function (){
                if(xhr.readyState === 4 && xhr.status === 200){
                    let responseText = xhr.responseText;
                    let span = document.getElementById("text2");
                    span.innerHTML = responseText;
                    if(span.innerHTML === true){
                        flag = false;
                        return flag

                    }
                    else {
                        flag = true;
                        return flag
                    }
                }
            }
        }

        // 向发送邮件
        function send_main() {
            // 向后台发送请求，向邮箱内发送邮件
            let flag = checkEmail();
            let email = $("[name='email']").val();
            // 如果flag为true，则代表邮箱格式合法，才发送邮件
            if (flag === true) {
                $.ajax({
                    url: "{% url 'user:send_email' %}",
                    type: 'get',
                    data: "email=" + email,
                    success: function (msg) {
                        console.log(msg);
                    }
                })
            }

        }

        // 发起注册请求
        function register() {
            let flag1 = checkPwd();
            let flag2 = checkEmail();
            let flag3 = checkPhone();
            if (flag1 === true && flag2 === true && flag3 === true) {
                // 提交当前页面的表单
                document.forms[0].submit();
            }
        }

        function fn1() {
        let img = document.getElementsByTagName('img')[0];
        img.src = "/user/captcha/" + "?" + new Date().getTime();
        //区别每个验证码
    }

    </script>
</head>
<body>
<div id="wrap">
    <div id="top_content">
        <div id="header">
            <div id="rightheader">
                <p>2009/11/20<br/></p>
            </div>
            <div id="topheader">
                <h1 id="title"><a href="#">main</a></h1>
            </div>
            <div id="navigation"></div>
        </div>
        <div id="content">
            <p id="whereami"></p>
            <h1>注册</h1>
            <form action="{% url 'user:user_register' %}" method="post">
                {% csrf_token %}
                <table cellpadding="0" cellspacing="0" border="0"
                       class="form_table">
                    <tr>
                        <td valign="middle" align="right">邮箱:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="email" onblur="checkEmail(this)"/>
                            <span id="text1" style="color: red"></span>
                            <br>
                            <input type="button" value="获取邮箱验证码" onclick="send_main()">
                            <span id="email_msg" style="color: #CE090E"></span>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">手机号:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="phone" onblur="checkPhone(this)"/>
                            <span id="text2" style="color:red"></span>
                            <span id="phone_msg" style="color: #CE090E"></span>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">密码:</td>
                        <td valign="middle" align="left">
                            <input type="password" class="inputgri" name="user_pwd" onblur="checkPwd()"/>
                            <span id="pwd_msg" style="color: #CE090E"></span>
                        </td>
                    </tr>
                    <tr>
                        <td valign="middle" align="right">
                            性别:
                        </td>
                        <td valign="middle" align="left">
                            男
                            <input type="radio" class="inputgri" name="sex" value="m" checked="checked"/>
                            女
                            <input type="radio" class="inputgri" name="sex" value="f"/>
                        </td>
                    </tr>

                    <tr>
                        <td valign="middle" align="right">邮箱验证码:</td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="email_code"/>
                        </td>
                    </tr>

                    <tr>
                        <td valign="middle" align="right">
                            验证码:
                        </td>
                        <td valign="middle" align="left">
                            <input type="text" class="inputgri" name="number"/>
                        </td>
                        <td>
                            <img id="num" src="/user/captcha/" alt="无法加载" width="100"/>
                            <a href="javascript:;" onclick=fn1()>换一张</a>
                        </td>
                    </tr>
                </table>
                <p>
                    <input type="button" class="button" value="注册" onclick="register()"/>
                </p>
            </form>
        </div>
    </div>
    <div id="footer">
        <div id="footer_bg">
            ABC@126.com
        </div>
    </div>
</div>
</body>
</html>